# Adapted from https://github.com/jdblischak/smk-simple-slurm
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --ntasks=1
    --cpus-per-task={threads}
    --mem-per-cpu={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.time}
default-resources:
  - mem_mb=4000
  - time="01:15:00"


cluster-cancel: scancel
cluster-cancel-nargs: 50
jobs: 200
max-jobs-per-second: 10
local-cores: 1
use-envmodules: True