cappseq_umi_workflow:
  refgenome: "__UPDATE__"  # Should contain BWA indicies and samtools fai index in the same directory
  captureregions: "__UPDATE__"
  captureregionsil: "__UPDATE__"  # Picard Interval List
  dbsnpvcf: "__UPDATE__"  # Should be BGzipped and TABIX indexed
  normalbam: "__UPDATE__"

  fgbio: "__UPDATE__"
  vcf2maf: "__UPDATE"
  vardict: "__UPDATE__"

  # Input and output
  samplefile: "config/samplelist.tsv"
  baseoutdir: "__UPDATE__"
  datadir: "__UPDATE__"

  readgroup:
    centre: "__UPDATE__"
    platformunit: "ILLUMINA"
    platformmodel: "NOVASEQ"
    description: "CAPPSeq of lymphoma-associated genes"

  # Threads
  bwa_threads: 24
  duplexconsensus_threads: 12
  samtools_sort_threads: 8
  basequal_threads: 4
  fgb_groupumi: 12
  picard_annot_threads: 4
  vardict_threads: 4

  # Barcode an duplex information
  barcodelength: "8"
  barcodelocation: "8M+T"  # Location of the barcode. See https://github.com/fulcrumgenomics/fgbio/wiki/Read-Structures
  umiedits: "2"  # Would be warry of changing
  minreads: "0"  # DO NOT SET TO x UNLESS YOU WANT AT LEAST x READ(S) FROM **EACH** STRAND

  # Cleanup and sanitization
  max_base_qual: 70
  tags_to_remove: {'ad', 'ac', 'bd', 'ae', 'be', 'bq', 'bc', 'aq'}

  multiqc_config: "config/multiqc_config.yaml"
